### ISSUE TITLE
Content assist doesn't offer keyword "method" in Franca IDL editor.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [franca/franca#49] opened 2015-07-31 13:32 UTC
```
Create an interface with only one attribute. Activate Content Assist after the 
attribute definition. "method" will not be offered.

```

Original issue reported on code.google.com by `klaus.birken@gmail.com` on 21 Jun 2013 at 7:50

**Comment by kbirken** [comment] 2018-04-07 20:02
This is fixed since Franca 0.9.1, as a side effect of issue #104 (relaxing the order of interface contents). There might be also another cause for this problem by the behavior of older Xtext versions (as used in 2015 when this issue has been created). Nowadays, we are using at least Xtext 2.11, the problem cannot be reproduced anymore. Closing.

**Closed by kbirken** 2018-04-07 20:02 UTC
Labels: Priority-Low, auto-migrated, bug
