### ISSUE TITLE
deployment model: duplicate method generated (low prio)

### ISSUE THREAD

**Issue by awarnke** [franca/franca#162] opened 2015-09-12 07:22 UTC
Hi,
When defining 

    for attributes {
        MaxBufferSize: Integer (default: 4096 );
    }
    for struct_fields {
        MaxBufferSize: Integer (default: 4096 );
    }
    for union_fields {
        MaxBufferSize: Integer (default: 4096 );
    }
    for arguments {
        MaxBufferSize: Integer (default: 4096 );
    }

This causes a duplicate method getMaxBufferSize(FField obj); for union_fields and struct_fields in Deploymentspec.IDataPropertyAccessor

Whereas the others (structs and attributes and arguments work fine, due to different types in method signature)

By the way: it is cool that in franca 0.10 the hosts byte_buffer and union_fields exist!

**Comment by kbirken** [comment] 2015-10-30 15:51
This is (nearly) a duplicate of issue 101. See my latest comment to issue 101 to get an update on the current state of this topic and what you may expect for Franca 0.10.1. 

Here are some comments regarding your example above, with Franca 0.9.2 or later: Yes, struct_fields and union_fields must not have properties with the same name, because this will result in a "collision" of getter methods in the PropertyAccessor. There is no conceptual solution for this, because if the type of the property (the return value of the getter) is different for both getters, there is no way to represent this in nice API code. In your specific example the methods could be merged (because they have the same type), but this would make the set of restrictions even more complicated as they are already.

With Franca 0.10.1, we will add validation checks which would show the collision of the properties in union_fields and struct_fields already in the model (as error markers). Thus, the generater will not run if collisions would occur in the resulting code.

In your case it would help to have a property host "fields" which is a combination of struct_fields and union_fields. What do you think?

**Comment by awarnke** [comment] 2015-10-30 20:53
Hello Klaus,
If an additional "fields" host is easier to implement - this would solve it and be compatible with the FField type definition. An alternative might be to split the FField type to FUnionField and FStructField.
Do not know what is easier - but both would solve the minor problem.
cu
Andreas

PS: I had not recognized the duplicate https://github.com/franca/franca/issues/101 - wording is different ;-)

**Comment by awarnke** [comment] 2015-10-31 10:46
Just a comment on my priority: I do not need a solution for issue https://github.com/franca/franca/issues/162 for ipc-quartztime, because the byte_buffers host provides a very nice solution for me:

    for byte_buffers {
        MaxBufferSize: Integer (default: 4096 );
    }

**Comment by kbirken** [comment] 2016-05-07 22:48
Implemented new property host "fields" with commit b5d8913.

**Closed by kbirken** 2016-05-07 22:48 UTC
Labels: duplicate
