### ISSUE TITLE
Escaping of Franca keywords in deployment doesn´t work

### ISSUE THREAD

**Issue by mbathelt** [franca/franca#160] opened 2015-08-25 13:58 UTC
In Franca IDL (fidl) there is the escape character "^" to escape Franca keywords used as element names. In the Franca deployment this does not work/exist.
It is not possible to deploy an interface like the example below, although the IDL is happy with this definition:

interface ^interface {
   method ^method {
      out {
         UInt8 instance
         String provider
      }}

In the example even the "instance" or "provider" used as parameter name are not deployable, because their name cannot be referenced in the deployment definition without causing another keyword collision.

The "^" escaping should be available in the deployment, otherwise none of the Franca keywords may be used anywhere in a Franca element, which is a quite tough restriction especially in case of parameter names.

**Comment by mbathelt** [comment] 2015-08-26 08:30
seems Issue #157 is same problem - sorry for raising an issue again - I´m not yet really used to github´s issue tracker.

**Comment by kbirken** [comment] 2015-10-23 12:31
Duplicate of #157, closing issue.

**Closed by kbirken** 2015-10-23 12:31 UTC
